# Generated by Django 2.1.7 on 2019-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(default=555, max_length=20),
            preserve_default=False,
        ),
    ]
