# Generated by Django 2.1.7 on 2019-02-26 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=None, max_length=50)),
                ('choice', models.CharField(default=None, max_length=50)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MatchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('match_task_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Matching tasks',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('question_name', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=None, max_length=50)),
                ('choice', models.CharField(default=None, max_length=50)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('all_time_opened', models.BooleanField(default=False)),
                ('test_opening_date', models.DateTimeField()),
                ('test_closing_date', models.DateTimeField(default=datetime.datetime(2019, 2, 26, 10, 39, 23, 289271, tzinfo=utc))),
                ('students', models.ManyToManyField(to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TFStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=50)),
                ('True?', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TFTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tf_tasks', to='studying.Testing')),
            ],
            options={
                'verbose_name_plural': 'True/False tasks',
            },
        ),
        migrations.CreateModel(
            name='WordBoxTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('without_wordbox', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_boxes', to='studying.Testing')),
            ],
        ),
        migrations.AddField(
            model_name='tfstatement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tf_stats', to='studying.TFTask'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='match_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='studying.WordBoxTask'),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multis', to='studying.Testing'),
        ),
        migrations.AddField(
            model_name='matchtask',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='studying.Testing'),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='match_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_options', to='studying.MatchTask'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='multis_choices', to='studying.MultiChoiceQuestion'),
        ),
    ]
