# Generated by Django 2.1.7 on 2019-03-05 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='test_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 20, 20, 49, 393663, tzinfo=utc)),
        ),
    ]
