# Generated by Django 2.1.7 on 2019-03-05 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0002_auto_20190305_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='test_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 20, 22, 34, 582490, tzinfo=utc)),
        ),
    ]
