# Generated by Django 2.1.7 on 2019-03-06 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0005_auto_20190305_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfstatement',
            name='task',
        ),
        migrations.AlterField(
            model_name='testing',
            name='test_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 9, 56, 40, 806522, tzinfo=utc)),
        ),
    ]
