# Generated by Django 2.1.7 on 2019-03-06 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0006_auto_20190306_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tftask',
            name='test',
        ),
        migrations.AddField(
            model_name='tfstatement',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tf_tasks', to='studying.Testing'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='test_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 10, 2, 52, 149857, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TFTask',
        ),
    ]
